name: DocSearch crawler

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  index:
    runs-on: ubuntu-latest

    name: Crawl docs for DocSearch

    steps:
      - uses: actions/checkout@v4

      - name: Crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.10
        id: index_after_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: "https://sphinx-docsearch.readthedocs.io/"
          crawler-name: "sphinx test"
